### ISSUE TITLE
Update to 1.20

### ISSUE THREAD

**Issue by Ryhon0** [kregerl/Replanter#14]
I've already updated the mod in my fork and tested it and it works properly 
https://github.com/Ryhon0/Replanter/tree/fabric1.20

**Comment by Soctentar** [comment]
Hi, I created a GitHub account just to ask this question.
I'm a total noob at coding and modding, so how do I make the .jar file out of this?
That or do you have a download link somewhere I could use? Thanks!

**Comment by Ryhon0** [comment]
It doesn't look like the owner of this project is interested in it anymore so I'm working on my own fork that adds 1.20 support and hopefully more features. It's available on https://github.com/Ryhon0/ReplanterPlus
and on Modrinth once it gets approved https://modrinth.com/mod/replanter-plus

**Comment by Soctentar** [comment]
Awesome!

-------- Original Message --------
