### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by chrisgates301** [kregerl/Replanter#3]
Could we have a config option where there is no need to have a seed in your offhand? Simply right click the crop with....say....a Fortune III hoe, and if the crop is going to give 5 seeds, make it give 1 seed less

**Comment by kregerl** [comment]
Unfortunately no, this would not be possible while keeping the mod client-side.

**Comment by chrisgates301** [comment]
What if im playing single-player offline? Would it still need to be client-side?

**Comment by kregerl** [comment]
The intention is to keep the mod completely client-side. If you want a mod for harvesting crops on right click without holding seeds, you could check out(Assuming Fabric) https://www.curseforge.com/minecraft/mc-mods/rightclickharvest-fabric.
